#!/usr/bin/env python
import sys

tp, fp, tn, fn = 0, 0, 0, 0
with open(sys.argv[1], 'r') as f:
  for line in sys.stdin:
    label, word, defn, example, voting = line.strip().split("|||")
    rlabel, rword, rdefn, rexample, rvoting = f.readline().strip().split("|||")
    gold = 1 if rlabel == 'n' else -1
    system = 1 if label == 'n' else -1
    if gold < 0:
      if system < 0:
        tn += 1
      else:
        fn += 1
    else:
      if system > 0:
        tp += 1
      else:
        fp += 1

precision = float(tp) / (tp + fp)
recall = float(tp) / (fn + tp)
fscore = 2 * (precision * recall) / (precision + recall)
      
print "Precision: %f | Recall : %f | F1-Score: %f" % (precision, recall, fscore)
